### ISSUE TITLE
Submitting discussion posts and code

### ISSUE THREAD

**Issue by kayvee** [stefanbund/cis155#21]
Hi Prof. @stefanbund 

I've noticed that we haven't been able to submit our code for Milestones 3/4 or Phase 2 or our discussion posts since week 6. Will those be opened up soon?

Thank you!
Kaveh

**Comment by stefanbund** [comment]
Yes

From Stefan

**Comment by kayvee** [comment]
@stefanbund 

Thank you so much. I saw that they were opened. I just had two questions:

1) for Phase 2, since there weren't submissions for Milestone 3 and 4, I didn't save them separately since it's all the same code. Should I just submit the same thing for Milestone 3, 4, and Phase 2?

2) There are submission links for Phase 3, but we didn't have to do this correct? We removed it and made Phase 2 the last part?

**Comment by stefanbund** [comment]
That's my fault. Go ahead and submit your finished projects for the milestone. I will give you credit for your latest work instead. My bad

From Stefan

**Comment by kayvee** [comment]
@stefanbund 

Thank you again!

I was wondering if you knew when grades would be added to our transcripts? I am submitting them for graduate school and was hoping to wait until they were finalized.

**Comment by stefanbund** [comment]
Grades will be submitted by the second, and available soon after. You might ask the registrar the same question, she will know when the transcript will be updated.

From Stefan

**Comment by forrestbennett** [comment]
Grades are in. Anyone check their grade yet? Not sure if I am the only one with an issue. Professor can please get back to me? I sent you an email. Thanks!
