### ISSUE TITLE
Install Java

### ISSUE THREAD

**Issue by bradleytran2015** [stefanbund/cis155#3]
Hi Everyone,
I went to Oracle Website and download Java SE Development Kit 8u73.
I downloaded Eclipse IDE for Java EE Developers from Eclipse.org.
First, I installed Java, and then extract Eclipse.
I did not have any problem while installing Java and Eclipse.
This is the picture of Eclipse and Java after installing them. 

![image](https://cloud.githubusercontent.com/assets/16991031/12876193/cceca2d4-cdb0-11e5-9bcc-cb5e965db522.png)

**Comment by stefanbund** [comment]
Nice work 🤓

From Stefan

**Comment by forrestbennett** [comment]
Very helpful, thank you Bradley
