### ISSUE TITLE
Project Roadmap; Milestone submission

### ISSUE THREAD

**Issue by kayvee** [stefanbund/cis155#6]
Re: Project Roadmap

https://github.com/stefanbund/cis155/blob/master/CIS%20155%20project%20roadmap.pdf

It seems that the Roadmap is cut off after Page 2, as it stops mid-sentence. Is this just an error I'm seeing?
## 

Re: Milestones

Where do we turn in Milestones? Milestone 1 is due at the end of this week, correct?

Thank you!

**Comment by stefanbund** [comment]
Yes, you are correct about the milestone submission time. Please have it done by this Sunday, midnight

From Stefan

**Comment by stefanbund** [comment]
Git hub tries to display PDF content, but if it cuts off, just click on the button that says 'raw' in the mid right-hand corner. This will give you an actual copy of the document, which is complete. Phase 3  has some details yet to be filled in, however.

From Stefan

**Comment by kayvee** [comment]
Perfect; thank you so much!
