### ISSUE TITLE
Where are the due dates?

### ISSUE THREAD

**Issue by calvinln** [stefanbund/cis155#7]
Hi

I searched through the course website and all the documents on Github, but failed to find due dates for all the assignments. The close date for all dropbox submissions is 5/29, which I believe is not the real due date. The start date for Milestone One is listed as 2/15 on this page http://seaport.coastline.edu/Ext/Courses/Browse/index.cfm?OpenDiv=Lessons, but in the milestone guide it says it's due this weekend. Which one should we trust? Also are there due dates for submissions of discussion screenshots too? What's the policy for late submissions?

One little suggestion: now that we use Github to store all the course documents, it would be much clearer if markdown is used rather than word/pdf.
- Markdown is supported by Github natively, while word/pdf files are not displayed well.
- When a Markdown file is changed by the instructor, students can check the diff to find out exactly what's updated. It's not possible with word/pdf files.

Calvin

**Comment by stefanbund** [comment]
The due date is as written, February 15

From Stefan

**Comment by stefanbund** [comment]
Thanks for closing this, I hope my question was helpful. Please ask many questions, without hesitation! 😎

From Stefan
