### ISSUE TITLE
Dropbox vs Github?

### ISSUE THREAD

**Issue by WesleyTo** [stefanbund/cis155#8]
Hi,

I was wondering why we're using Word/PDFs in a dropbox to submit code instead of just committing and pushing to a Github repo.

I don't have a problem with it (well, I did have problems getting my PDF plugin to work and acquiring Word-compatible software, but that's been fixed). It just seems weird to me that we're using Github for everything _except_ code submission, so I was wondering if there was a reason.

-Wes

**Comment by stefanbund** [comment]
The instructions are there to be followed. This is wh:; word and pdfs are highly readable.  Once I view your console output, I will look for reasons why it appeared as such in the source code.

 Your role as an undergraduate is to produce highly understandable work. This is one such assignment. 

Another note on github; git to synchronizes code between coworkers who are submitting code. We are using its facility as a discussion medium, which alerts me whenever you have comments. If I were to have you submit code in this way, it would be available for the open Internet to read. Not helpful!

 Any other questions?

From Stefan

**Comment by WesleyTo** [comment]
Stefan,

Now that you say it makes seeing the output and following the code easier, it makes more sense why you do it this way. 

With regards to Github, I asked because I’ve done code submission on Github/Bitbucket before with private repos and the instructor added as a collaborator (students get free private repos). The instructor can then pull the latest commit at the deadline, all while the code remains hidden from everyone else. But, in this case, without standardized output and some sort of auto-grader, the drawback is that you would have to manually run the code and inspect the output. With the Word/PDF, that's already been done.

Thanks!
-Wes

**Comment by stefanbund** [comment]
My ideal would to have an applet that runs your code, so I can see it running. Otherwise, I use the output as evidence.

From Stefan
